---
title: "Day XX Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(readr)
library(ds4psy)
library(numbers)
options(scipen = 999)
```


## Part 1
change this into a dataframe (of course)
```{r}
input<-read_lines("Day4Sample.txt")
secassign<-as.data.frame(matrix(nrow=0,ncol=4))
for(i in 1:length(input)){
  secassign<-rbind(secassign,as.numeric(unlist(str_split(input[i],"[-,]"))))}
colnames(secassign)<-c("oneleft","oneright","twoleft","tworight")
```

Then find if anything is enclosed entirely
```{r}
secassign<-secassign %>% rowwise %>%
  mutate(enclosed=ifelse(((oneleft<=twoleft&&oneright>=tworight)||(twoleft<=oneleft&&tworight>=oneright)),1,0))
part1<-sum(secassign$enclosed)
part1
```
## Part 2
find if there's anything that overlaps at all.  As long as the left of one side is bigger than the right of the other, there won't be an overlap.
```{r}
secassign<-secassign %>% rowwise %>%
  mutate(overlap=ifelse(((oneleft>tworight)||(twoleft>oneright)),0,1))
part2<-sum(secassign$overlap)
part2
```
