---
title: "Day XX Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(readr)
library(ds4psy)
library(numbers)
options(scipen = 999)
```



This has recursion written all over it....

```{r}
input<-read_lines("Day13Sample.txt")
```

First, prep the data

```{r}
prepinput<-sapply(input,function(x){
  #remove the commas and replace with spaces
  #add spaces around the brackets
  y<-str_replace_all(x,","," ")
  y<-str_replace_all(y,"\\["," \\[ ")
  y<-str_replace_all(y,"\\]"," \\] ")
  y<-str_squish(y)
  y})

lefts<-list()
rights<-list()
```


```{r}
for(i in seq(from=1,to=length(prepinput),by=3)){
  lefts<-c(lefts,c(str_split(prepinput[i]," ")))
  rights<-c(rights,c(str_split(prepinput[i+1]," ")))}
```
## Part 1

start with a function that says which should come first

```{r}
leftorright<-function(left,right){
  nums<-c("0","1","2","3","4","5","6","7","8","9")
  #trim leading spaces
  ### if either left or right is empty, it comes first.
  ### check if we've reached the end
  if(length(left)==0){return("left")
  } else if (length(right)==0){
    return("right")
    ### check if this is the end of a list
  }else{
    l1<-left[1]
    r1<-right[1]
    if(l1=="]"&&r1!="]"){
      return("left")
    }else if(r1=="]"&&l1!="]"){
      return("right")
      ### if both at the end or both at the beginning, dump first char & do it again.
    }else if((r1=="]"&&l1=="]")||(r1=="["&&l1=="[")){
      leftorright(left[-1],right[-1])
      ##  if one a list and the other is not. just remove the opening bracket 
    }else if(r1=="["&&l1!="["){
      leftorright(c(left[1],"]",left[-1]),right[-1])
    }else if(l1=="["&&r1!="["){
      leftorright(left[-1],c(right[1],"]",right[-1]))
    }else{
      l1<-as.numeric(l1)
      r1<-as.numeric(r1)
      if(l1<r1){return("left")
      }else if(r1<l1){return("right")
      }else{leftorright(left[-1],right[-1])}}}}
```


apply to the input
```{r}
part1<-sapply(1:((length(input)%/%3)+1),function(x){
  leftorright(lefts[[x]],rights[[x]])})
```

because the "lefts" are correct, sum the indicies of the lefts
```{r}
part1<-sum(which(part1=="left"))
part1
```
##Part 2
it's possible to sort this, but it's really not necessary.
for both [[2]]&[[6]], run those on against all of the input (left and right). Find out how many would go before.
[[2]] will be 1 plus the number before
[[6]] will be 2 plus the number before (1 for the number, 1 for the [[2]])
```{r}
##transform into the right format
bracket2<-c("[","[","2","]","]")
bracket6<-c("[","[","6","]","]")

## combine lefts and rights
allpackets<-c(lefts,rights)

## run against the packets
b2<-sapply(allpackets,function(x){leftorright(x,bracket2)})
b6<-sapply(allpackets,function(x){leftorright(x,bracket6)})

## count the lefts
b2<-table(b2)["left"]+1
b6<-table(b6)["left"]+2
part2<-unname(b2*b6)
part2
```

